apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJWakNCL3FBREFnRUNBZ0VBTUFvR0NDcUdTTTQ5QkFNQ01DTXhJVEFmQmdOVkJBTU1HR3N6Y3kxelpYSjIKWlhJdFkyRkFNVFU1TURZMU5qUTVOVEFlRncweU1EQTFNamd3T1RBeE16VmFGdzB6TURBMU1qWXdPVEF4TXpWYQpNQ014SVRBZkJnTlZCQU1NR0dzemN5MXpaWEoyWlhJdFkyRkFNVFU1TURZMU5qUTVOVEJaTUJNR0J5cUdTTTQ5CkFnRUdDQ3FHU000OUF3RUhBMElBQk5CdUE2ZEh2eWk0Zi80VnlzMERqc3FXZzkzYkt1ZGlvVERrcWs4Wk9qZysKczNINCtIWUZvUG0yVWZqNmpDQVc2MTIzSjBIVEZqMm52aDluNXREbGZqV2pJekFoTUE0R0ExVWREd0VCL3dRRQpBd0lDcERBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUFvR0NDcUdTTTQ5QkFNQ0EwY0FNRVFDSUVZK3JFdWhidVRqCnZlZWdPeU81T2FraEFzanBLZ1FLRkZkdUxVdkppSkd6QWlBM2VZS0d0d29DODBxNURTQ1NMdVliYlZVM0tMUWcKVERrZmh3djk4K2wrNmc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://192.168.1.90:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    password: 6bc83d58eb53c13ef7eead216b3cd454
    username: admin
