apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJWekNCL3FBREFnRUNBZ0VBTUFvR0NDcUdTTTQ5QkFNQ01DTXhJVEFmQmdOVkJBTU1HR3N6Y3kxelpYSjIKWlhJdFkyRkFNVFU1TVRrMU5EY3lNVEFlRncweU1EQTJNVEl3T1RNNE5ERmFGdzB6TURBMk1UQXdPVE00TkRGYQpNQ014SVRBZkJnTlZCQU1NR0dzemN5MXpaWEoyWlhJdFkyRkFNVFU1TVRrMU5EY3lNVEJaTUJNR0J5cUdTTTQ5CkFnRUdDQ3FHU000OUF3RUhBMElBQktBNEZjVjJvNm96MC9VVE93b1pKWWxQcDdzNWJjakJZeFVxdVlWZFdXUmwKOGZTVWVMZDlVVkJreEtXSGtDNmFUQ0psTElQZEppL1ZaeHFmbFFuK2UrS2pJekFoTUE0R0ExVWREd0VCL3dRRQpBd0lDcERBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSUFsSHFZeUdheTdzCitPRlU5Rms3UkZGQmhLaHFpODFZKzJjYTZiU1FyNmtKQWlFQXQ3VHZ0eTJya21WSkhqbmw0dVBMMXIydEd5QVMKZForWXhnbTkwMWYyTkhJPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://192.168.1.90:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    password: 0927b2b248801af2f51ea2987eb31581
    username: admin
