apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJWakNCL3FBREFnRUNBZ0VBTUFvR0NDcUdTTTQ5QkFNQ01DTXhJVEFmQmdOVkJBTU1HR3N6Y3kxelpYSjIKWlhJdFkyRkFNVFU1TWpNeU1UQXhOVEFlRncweU1EQTJNVFl4TlRJek16VmFGdzB6TURBMk1UUXhOVEl6TXpWYQpNQ014SVRBZkJnTlZCQU1NR0dzemN5MXpaWEoyWlhJdFkyRkFNVFU1TWpNeU1UQXhOVEJaTUJNR0J5cUdTTTQ5CkFnRUdDQ3FHU000OUF3RUhBMElBQkJCUzd3VzdIN0g1akpSRzRYb3E5Tmt2L0JGL2YrMk5ONjVJS0JXeGFrNTQKdEViVWhaNXgrZFFjQjJuckE5WTY1NlhBb2RMd0diNGhxK2VVUGMyR1ZxaWpJekFoTUE0R0ExVWREd0VCL3dRRQpBd0lDcERBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUFvR0NDcUdTTTQ5QkFNQ0EwY0FNRVFDSUZLbE1CVGg0ZXVXCjVRT1dVaHQwd0dTNTJ5SmNVQkVMM3UrMG1kNE5hczU1QWlCSG5WTzkyb2lseWU3S3cwUGloWjQ4dHNxTjJ6alMKWjV2WllHZUlsUGd2dGc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://192.168.1.90:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    password: fb2ccd52ec63f2c4d3ab8767711000bf
    username: admin
